BY THE ALMIGHTY GOD YOU CAN READ THIS MY FRIEND I AM IMPRESSED VERY WELL DONE YOUR SOLUTION KEY IS LMSPPHCLOHDB THIS LITTLE CHALLENGE WAS NOT TOO HARD WAS IT
HE LBP CZAGXBLE XRK ERU MCT SPCK LBGV AE NSGPTK G CA GAWSPVVPK FPSE DPZZ KRTP ERUS VRZULGRT YPE GV ZAVWWBMZRBKH LBGV ZGLLZP MBCZZPTXP DCV TRL LRR BCSK DCV GL

A > U
B > Y
C > F
D > B
E > E
F > G
G > W
H > O
I > X
K > L
